/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogConfig : Server-provided configuration for the catalog.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogConfig {
    /// Properties that should be used to override client configuration; applied after defaults and client configuration.
    #[serde(rename = "overrides")]
    pub overrides: std::collections::HashMap<String, String>,
    /// Properties that should be used as default configuration; applied before client configuration.
    #[serde(rename = "defaults")]
    pub defaults: std::collections::HashMap<String, String>,
    /// A list of endpoints that the server supports. The format of each endpoint must be \"<HTTP verb> <resource path from OpenAPI REST spec>\". The HTTP verb and the resource path must be separated by a space character.
    #[serde(rename = "endpoints", skip_serializing_if = "Option::is_none")]
    pub endpoints: Option<Vec<String>>,
}

impl CatalogConfig {
    /// Server-provided configuration for the catalog.
    pub fn new(
        overrides: std::collections::HashMap<String, String>,
        defaults: std::collections::HashMap<String, String>,
    ) -> CatalogConfig {
        CatalogConfig {
            overrides,
            defaults,
            endpoints: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::{json, Value};
    use std::collections::HashMap;

    #[test]
    fn test_catalog_config_serialises_overrides_and_defaults_as_objects() {
        let overrides = HashMap::from([("k1".to_string(), "v1".to_string())]);
        let defaults = HashMap::from([("k2".to_string(), "v2".to_string())]);
        let config = CatalogConfig::new(overrides, defaults);
        let value: Value = serde_json::to_value(&config).unwrap();
        assert_eq!(value["overrides"]["k1"], "v1");
        assert_eq!(value["defaults"]["k2"], "v2");
        // Empty endpoints is None, so the key is omitted.
        assert!(value.get("endpoints").is_none(), "got {value}");
    }

    #[test]
    fn test_catalog_config_empty_maps_render_as_empty_objects() {
        // Required keys are always present, even when their map is empty,
        // so the server contract stays predictable.
        let config = CatalogConfig::new(HashMap::new(), HashMap::new());
        let value: Value = serde_json::to_value(&config).unwrap();
        assert_eq!(value["overrides"], json!({}));
        assert_eq!(value["defaults"], json!({}));
    }

    #[test]
    fn test_catalog_config_serialises_endpoints_as_array_when_some() {
        let mut config = CatalogConfig::new(HashMap::new(), HashMap::new());
        config.endpoints = Some(vec![
            "GET /v1/{prefix}/namespaces".to_string(),
            "POST /v1/{prefix}/tables".to_string(),
        ]);
        let value: Value = serde_json::to_value(&config).unwrap();
        assert_eq!(
            value["endpoints"],
            json!(["GET /v1/{prefix}/namespaces", "POST /v1/{prefix}/tables",])
        );
    }

    #[test]
    fn test_catalog_config_round_trip_via_json() {
        let mut original = CatalogConfig::new(
            HashMap::from([("o.k".to_string(), "o.v".to_string())]),
            HashMap::from([("d.k".to_string(), "d.v".to_string())]),
        );
        original.endpoints = Some(vec!["GET /v1/config".to_string()]);
        let json = serde_json::to_string(&original).unwrap();
        let parsed: CatalogConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, original);
    }
}
