/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateNamespaceResponse {
    /// Reference to one or more levels of a namespace
    #[serde(rename = "namespace")]
    pub namespace: Vec<String>,
    /// Properties stored on the namespace, if supported by the server.
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
}

impl CreateNamespaceResponse {
    pub fn new(namespace: Vec<String>) -> CreateNamespaceResponse {
        CreateNamespaceResponse {
            namespace,
            properties: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::{json, Value};

    #[test]
    fn test_create_namespace_response_round_trip_with_properties() {
        let mut original = CreateNamespaceResponse::new(vec!["ns".to_string()]);
        original.properties = Some(std::collections::HashMap::from([(
            "k".to_string(),
            "v".to_string(),
        )]));
        let json = serde_json::to_string(&original).unwrap();
        let parsed: CreateNamespaceResponse = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, original);
    }

    #[test]
    fn test_create_namespace_response_omits_properties_key_when_none() {
        let response = CreateNamespaceResponse::new(vec!["ns".to_string()]);
        let value: Value = serde_json::to_value(&response).unwrap();
        assert_eq!(value["namespace"], json!(["ns"]));
        assert!(value.get("properties").is_none(), "got {value}");
    }
}
