/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListNamespacesResponse {
    /// An opaque token that allows clients to make use of pagination for list APIs (e.g. ListTables). Clients may initiate the first paginated request by sending an empty query parameter `pageToken` to the server. Servers that support pagination should identify the `pageToken` parameter and return a `next-page-token` in the response if there are more results available.  After the initial request, the value of `next-page-token` from each response must be used as the `pageToken` parameter value for the next request. The server must return `null` value for the `next-page-token` in the last response. Servers that support pagination must return all results in a single response with the value of `next-page-token` set to `null` if the query parameter `pageToken` is not set in the request. Servers that do not support pagination should ignore the `pageToken` parameter and return all results in a single response. The `next-page-token` must be omitted from the response. Clients must interpret either `null` or missing response value of `next-page-token` as the end of the listing results.
    #[serde(rename = "next-page-token", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    #[serde(rename = "namespaces", skip_serializing_if = "Option::is_none")]
    pub namespaces: Option<Vec<Vec<String>>>,
}

impl ListNamespacesResponse {
    pub fn new() -> ListNamespacesResponse {
        ListNamespacesResponse {
            next_page_token: None,
            namespaces: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::{json, Value};

    #[test]
    fn test_list_namespaces_response_empty_serialises_to_empty_object() {
        let response = ListNamespacesResponse::new();
        let value: Value = serde_json::to_value(&response).unwrap();
        // Both optional fields are None -> the JSON object is empty.
        assert_eq!(value, json!({}));
    }

    #[test]
    fn test_list_namespaces_response_serialises_nested_namespaces() {
        let mut response = ListNamespacesResponse::new();
        response.namespaces = Some(vec![
            vec!["analytics".to_string()],
            vec!["analytics".to_string(), "events".to_string()],
        ]);
        let value: Value = serde_json::to_value(&response).unwrap();
        assert_eq!(
            value["namespaces"],
            json!([["analytics"], ["analytics", "events"]])
        );
    }

    #[test]
    fn test_list_namespaces_response_uses_kebab_renamed_pagination_token() {
        let mut response = ListNamespacesResponse::new();
        response.next_page_token = Some("opaque-token-xyz".to_string());
        let value: Value = serde_json::to_value(&response).unwrap();
        assert_eq!(value["next-page-token"], "opaque-token-xyz");
    }

    #[test]
    fn test_list_namespaces_response_round_trip_with_pagination_and_namespaces() {
        let mut original = ListNamespacesResponse::new();
        original.next_page_token = Some("tok".to_string());
        original.namespaces = Some(vec![vec!["a".to_string(), "b".to_string()]]);
        let json = serde_json::to_string(&original).unwrap();
        let parsed: ListNamespacesResponse = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, original);
    }
}
