/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OAuthError : The `oauth/tokens` endpoint and related schemas are **DEPRECATED for REMOVAL** from this spec, see description of the endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthError {
    #[serde(rename = "error")]
    pub error: Error,
    #[serde(rename = "error_description", skip_serializing_if = "Option::is_none")]
    pub error_description: Option<String>,
    #[serde(rename = "error_uri", skip_serializing_if = "Option::is_none")]
    pub error_uri: Option<String>,
}

impl OAuthError {
    /// The `oauth/tokens` endpoint and related schemas are **DEPRECATED for REMOVAL** from this spec, see description of the endpoint.
    pub fn new(error: Error) -> OAuthError {
        OAuthError {
            error,
            error_description: None,
            error_uri: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "invalid_request")]
    InvalidRequest,
    #[serde(rename = "invalid_client")]
    InvalidClient,
    #[serde(rename = "invalid_grant")]
    InvalidGrant,
    #[serde(rename = "unauthorized_client")]
    UnauthorizedClient,
    #[serde(rename = "unsupported_grant_type")]
    UnsupportedGrantType,
    #[serde(rename = "invalid_scope")]
    InvalidScope,
}

impl Default for Error {
    fn default() -> Error {
        Self::InvalidRequest
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;

    #[test]
    fn test_oauth_error_variant_default_is_invalid_request() {
        assert_eq!(Error::default(), Error::InvalidRequest);
    }

    #[test]
    fn test_oauth_error_variants_serialise_with_underscore_canonical_tags() {
        // The OAuth 2.0 spec uses snake_case tags; serde renames each
        // variant to the exact RFC-defined string.
        let cases = [
            (Error::InvalidRequest, "\"invalid_request\""),
            (Error::InvalidClient, "\"invalid_client\""),
            (Error::InvalidGrant, "\"invalid_grant\""),
            (Error::UnauthorizedClient, "\"unauthorized_client\""),
            (Error::UnsupportedGrantType, "\"unsupported_grant_type\""),
            (Error::InvalidScope, "\"invalid_scope\""),
        ];
        for (variant, expected) in cases {
            let json = serde_json::to_string(&variant).unwrap();
            assert_eq!(json, expected, "variant {variant:?}");
            let parsed: Error = serde_json::from_str(&json).unwrap();
            assert_eq!(parsed, variant);
        }
    }

    #[test]
    fn test_oauth_error_new_initialises_with_just_the_variant() {
        let err = OAuthError::new(Error::InvalidGrant);
        assert_eq!(err.error, Error::InvalidGrant);
        assert!(err.error_description.is_none());
        assert!(err.error_uri.is_none());
    }

    #[test]
    fn test_oauth_error_omits_optional_fields_when_none() {
        let err = OAuthError::new(Error::InvalidScope);
        let value: Value = serde_json::to_value(&err).unwrap();
        assert_eq!(value["error"], "invalid_scope");
        assert!(value.get("error_description").is_none(), "got {value}");
        assert!(value.get("error_uri").is_none(), "got {value}");
    }

    #[test]
    fn test_oauth_error_round_trip_with_full_payload() {
        let mut original = OAuthError::new(Error::InvalidRequest);
        original.error_description = Some("missing client_id".to_string());
        original.error_uri =
            Some("https://example.com/oauth/error-docs#invalid_request".to_string());
        let json = serde_json::to_string(&original).unwrap();
        let parsed: OAuthError = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, original);
    }

    #[test]
    fn test_oauth_error_rejects_unknown_variant_tag() {
        let json = "\"frobnicate_token\"";
        assert!(serde_json::from_str::<Error>(json).is_err());
    }
}
