/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use iceberg_rust::catalog::identifier::Identifier;

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenameTableRequest {
    #[serde(rename = "source")]
    pub source: Identifier,
    #[serde(rename = "destination")]
    pub destination: Identifier,
}

impl RenameTableRequest {
    pub fn new(source: Identifier, destination: Identifier) -> RenameTableRequest {
        RenameTableRequest {
            source,
            destination,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::{json, Value};

    #[test]
    fn test_rename_table_request_serialises_source_and_destination_identifiers() {
        let req = RenameTableRequest::new(
            Identifier::parse("ns.old_name", None).unwrap(),
            Identifier::parse("ns.new_name", None).unwrap(),
        );
        let value: Value = serde_json::to_value(&req).unwrap();
        assert_eq!(value["source"]["name"], "old_name");
        assert_eq!(value["source"]["namespace"], json!(["ns"]));
        assert_eq!(value["destination"]["name"], "new_name");
        assert_eq!(value["destination"]["namespace"], json!(["ns"]));
    }

    #[test]
    fn test_rename_table_request_round_trip_via_json() {
        let original = RenameTableRequest::new(
            Identifier::parse("db.events_v1", None).unwrap(),
            Identifier::parse("db.events_v2", None).unwrap(),
        );
        let json = serde_json::to_string(&original).unwrap();
        let parsed: RenameTableRequest = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, original);
    }

    #[test]
    fn test_rename_table_request_supports_cross_namespace_move() {
        let req = RenameTableRequest::new(
            Identifier::parse("staging.daily_events", None).unwrap(),
            Identifier::parse("production.daily_events", None).unwrap(),
        );
        let value: Value = serde_json::to_value(&req).unwrap();
        assert_eq!(value["source"]["namespace"], json!(["staging"]));
        assert_eq!(value["destination"]["namespace"], json!(["production"]));
        // The table name does not change, only the namespace.
        assert_eq!(value["source"]["name"], "daily_events");
        assert_eq!(value["destination"]["name"], "daily_events");
    }
}
