//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

pub use super::catalog::Entity as Catalog;
pub use super::iceberg_table::Entity as IcebergTable;
pub use super::namespace::Entity as Namespace;
