/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use aws_credential_types::Credentials;
use aws_sigv4::http_request::{sign, SignableBody, SignableRequest, SigningError, SigningSettings};
use aws_sigv4::sign::v4;
use derive_builder::Builder;
use iceberg_rust::error::Error as IcebergError;
use secrecy::{ExposeSecret, SecretString};
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;
use std::time::SystemTime;

/// A closure that provides an OAuth access token asynchronously.
pub type OAuthAccessTokenProvider = Arc<
    dyn Fn() -> Pin<Box<dyn Future<Output = Result<String, IcebergError>> + Send>> + Send + Sync,
>;

#[derive(Clone, Builder)]
pub struct Configuration {
    pub base_path: String,
    #[builder(setter(into, strip_option), default)]
    pub user_agent: Option<String>,
    #[builder(default = "reqwest::Client::new()")]
    pub client: reqwest::Client,
    #[builder(setter(into, strip_option), default)]
    pub basic_auth: Option<BasicAuth>,
    #[builder(setter(strip_option), default)]
    pub oauth_access_token: Option<OAuthAccessTokenProvider>,
    #[builder(setter(into, strip_option), default)]
    pub bearer_access_token: Option<String>,
    #[builder(setter(into, strip_option), default)]
    pub api_key: Option<ApiKey>,
    #[builder(setter(into, strip_option), default)]
    pub aws_v4_key: Option<AWSv4Key>,
}

impl std::fmt::Debug for Configuration {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Configuration")
            .field("base_path", &self.base_path)
            .field("user_agent", &self.user_agent)
            .field("basic_auth", &self.basic_auth)
            .field(
                "oauth_access_token",
                &self.oauth_access_token.as_ref().map(|_| "..."),
            )
            .field("bearer_access_token", &self.bearer_access_token)
            .field("api_key", &self.api_key)
            .field("aws_v4_key", &self.aws_v4_key)
            .finish()
    }
}

pub type BasicAuth = (String, Option<String>);

#[derive(Debug, Clone)]
pub struct ApiKey {
    pub prefix: Option<String>,
    pub key: String,
}

#[derive(Debug, Clone)]
pub struct AWSv4Key {
    pub access_key: String,
    pub secret_key: SecretString,
    pub session_token: Option<SecretString>,
    pub region: String,
    pub service: String,
}

impl AWSv4Key {
    pub fn sign(
        &self,
        uri: &str,
        method: &str,
        body: &str,
    ) -> Result<Vec<(String, String)>, SigningError> {
        let credentials = Credentials::new(
            self.access_key.as_str(),
            self.secret_key.expose_secret(),
            self.session_token
                .as_ref()
                .map(|t| t.expose_secret().to_owned()),
            None,
            "iceberg-rest-catalog",
        );
        let identity = credentials.into();
        let signing_settings = SigningSettings::default();
        let signing_params = v4::SigningParams::builder()
            .identity(&identity)
            .region(self.region.as_str())
            .name(self.service.as_str())
            .time(SystemTime::now())
            .settings(signing_settings)
            .build()
            .unwrap()
            .into();
        let signable_request = SignableRequest::new(
            method,
            uri,
            std::iter::empty(),
            SignableBody::Bytes(body.as_bytes()),
        )?;
        let (signing_instructions, _signature) =
            sign(signable_request, &signing_params)?.into_parts();
        let additional_headers = signing_instructions
            .headers()
            .map(|(name, value)| (name.to_string(), value.to_string()))
            .collect();
        Ok(additional_headers)
    }
}

impl Default for Configuration {
    fn default() -> Self {
        Configuration {
            base_path: "https://localhost".to_owned(),
            user_agent: Some("OpenAPI-Generator/0.0.1/rust".to_owned()),
            client: reqwest::Client::new(),
            basic_auth: None,
            oauth_access_token: None,
            bearer_access_token: None,
            api_key: None,
            aws_v4_key: None,
        }
    }
}

impl Configuration {
    /// Resolve the OAuth access token by calling the provider closure, if set.
    pub async fn resolve_oauth_token(&self) -> Result<Option<String>, IcebergError> {
        match &self.oauth_access_token {
            Some(provider) => provider().await.map(Some),
            None => Ok(None),
        }
    }
}
