//! Main library entry point for openapi_client implementation.
use std::env;

use hyper::server::conn::Http;
use hyper::service::Service;
use sea_orm::DatabaseConnection;
use swagger::auth::MakeAllowAllAuthenticator;
use swagger::EmptyContext;
use tokio::net::TcpListener;

#[cfg(not(any(target_os = "macos", target_os = "windows", target_os = "ios")))]
use openssl::ssl::{Ssl, SslAcceptor, SslFiletype, SslMethod};

use iceberg_catalog_rest_rdbms_server::server::MakeService;

use clap::Parser;

mod api;
mod database;

#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// Host
    #[arg(long)]
    host: Option<String>,
    /// Port
    #[arg(short, long)]
    port: Option<String>,
    /// Https flag
    #[arg(long)]
    https: bool,
}

/// Create custom server, wire it to the autogenerated router,
/// and pass it to the web server.
#[tokio::main]
async fn main() {
    env_logger::init();

    let db_type = env::var("DB_TYPE").unwrap_or("postgres".to_owned());
    let db_user = env::var("DB_USER").unwrap_or("postgres".to_owned());
    let db_password = env::var("DB_PASSWORD").expect("Database password has to be provided");
    let db_host = env::var("DB_HOST").expect("Database host has to be provided");
    let db_port = env::var("DB_PORT").unwrap_or("5432".to_owned());

    let db_name = env::var("DB_NAME").unwrap_or("iceberg_catalog".to_owned());

    let db_connection =
        db_type + "://" + &db_user + ":" + &db_password + "@" + &db_host + ":" + &db_port;

    let db = database::run(&db_connection, &db_name).await.unwrap();

    let args = Args::parse();

    let host = args.host.unwrap_or_else(|| "0.0.0.0".to_owned());

    let port = args.port.unwrap_or_else(|| "8080".to_owned());

    let addr = host + ":" + &port;

    create(&addr, args.https, db).await;
}

/// Builds an SSL implementation for Simple HTTPS from some hard-coded file names
pub async fn create(addr: &str, https: bool, db: DatabaseConnection) {
    let addr = addr.parse().expect("Failed to parse bind address");

    let server = api::Server::new(db);

    let service = MakeService::new(server);

    let service = MakeAllowAllAuthenticator::new(service, "cosmo");

    #[allow(unused_mut)]
    let mut service = iceberg_catalog_rest_rdbms_server::server::context::MakeAddContext::<
        _,
        EmptyContext,
    >::new(service);

    if https {
        #[cfg(any(target_os = "macos", target_os = "windows", target_os = "ios"))]
        {
            unimplemented!("SSL is not implemented for the examples on MacOS, Windows or iOS");
        }

        #[cfg(not(any(target_os = "macos", target_os = "windows", target_os = "ios")))]
        {
            let mut ssl = SslAcceptor::mozilla_intermediate_v5(SslMethod::tls())
                .expect("Failed to create SSL Acceptor");

            // Server authentication
            ssl.set_private_key_file("examples/server-key.pem", SslFiletype::PEM)
                .expect("Failed to set private key");
            ssl.set_certificate_chain_file("examples/server-chain.pem")
                .expect("Failed to set certificate chain");
            ssl.check_private_key()
                .expect("Failed to check private key");

            let tls_acceptor = ssl.build();
            let tcp_listener = TcpListener::bind(&addr).await.unwrap();

            loop {
                if let Ok((tcp, _)) = tcp_listener.accept().await {
                    let ssl = Ssl::new(tls_acceptor.context()).unwrap();
                    let addr = tcp.peer_addr().expect("Unable to get remote address");
                    let service = service.call(addr);

                    tokio::spawn(async move {
                        let tls = tokio_openssl::SslStream::new(ssl, tcp).map_err(|_| ())?;
                        let service = service.await.map_err(|_| ())?;

                        Http::new()
                            .serve_connection(tls, service)
                            .await
                            .map_err(|_| ())
                    });
                }
            }
        }
    } else {
        // Using HTTP
        hyper::server::Server::bind(&addr)
            .serve(service)
            .await
            .unwrap()
    }
}
