/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use iceberg_rust::catalog::{
    commit::{TableRequirement, TableUpdate},
    identifier::Identifier,
};

use crate::models;

#[derive(Default, Debug, Serialize, Deserialize)]
pub struct CommitTableRequest {
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<Box<Identifier>>,
    #[serde(rename = "requirements")]
    pub requirements: Vec<TableRequirement>,
    #[serde(rename = "updates")]
    pub updates: Vec<TableUpdate>,
}

impl CommitTableRequest {
    pub fn new(
        requirements: Vec<TableRequirement>,
        updates: Vec<TableUpdate>,
    ) -> CommitTableRequest {
        CommitTableRequest {
            identifier: None,
            requirements,
            updates,
        }
    }
}
