/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterTableRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "metadata-location")]
    pub metadata_location: String,
}

impl RegisterTableRequest {
    pub fn new(name: String, metadata_location: String) -> RegisterTableRequest {
        RegisterTableRequest {
            name,
            metadata_location,
        }
    }
}

